/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jvahorcado;

import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author efras
 */
public class jfrmAhorcado extends javax.swing.JFrame {
    URL urlImagen;
    clsAhorcado objAhorcado;
    DefaultListModel lstPalabras;
    String valorLstP = "";
    boolean repetirPalabra = true;
    String[][]arrPalabras;
    String[] imagenesAhorcado = {"/imagenes/ahorcado_00.png", "/imagenes/ahorcado_01.png", "/imagenes/ahorcado_02.png", "/imagenes/ahorcado_03.png", "/imagenes/ahorcado_04.png", "/imagenes/ahorcado_05.png", "/imagenes/ahorcado_06.png"};
    String guionesPalabras;

    /**
     * Creates new form jfrmAhorcado
     */
    public jfrmAhorcado() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.jlblAhorcado.setBackground(Color.WHITE);
        mostrarImagen(jlblLogo, "/imagenes/logo.jpg");
        this.jtxtNumPalabras.setEditable(false);
        this.jbtnIngresarLetra.setEnabled(false);
        this.jbtnJugar.setEnabled(false);
        this.jbtnLimpiar.setEnabled(false);
        lstPalabras = new DefaultListModel();
        jlstPalabras.setModel(lstPalabras);
        objAhorcado = new clsAhorcado();
        actualizarImagen();
    }
    public void mostrarImagen(JLabel imagenLogo, String urlImg){
        urlImagen = this.getClass().getResource(urlImg);
        ImageIcon imgL = new ImageIcon(urlImagen);
        Icon imagen = new ImageIcon(imgL.getImage().getScaledInstance(imagenLogo.getWidth(), imagenLogo.getHeight(), Image.SCALE_DEFAULT));
        imagenLogo.setIcon(imagen);
        //no se ve
        this.repaint();
    } 
    public void limpiarControles(){
        lstPalabras.clear();
        jtxtNumPalabras.setText("");
        jlblIntentosFallos.setText("");
        jlblPalabraSelec.setText("");
        this.jbtnIngresarLetra.setEnabled(false);
        this.jbtnJugar.setEnabled(false);
        this.jbtnLimpiar.setEnabled(false);
        actualizarImagen();
    }
    public void actualizarGuiones(){
        guionesPalabras = "";
        for (int i = 0; i < objAhorcado.getLetrasPlabra()[0].length; i++) {
            if (objAhorcado.getLetrasPlabra()[1][i] == '0') {
               guionesPalabras += objAhorcado.getLetrasPlabra()[0][i] + "   "; 
            }else{
              guionesPalabras += "_   ";
            }
        }
        jlblPalabraSelec.setText(guionesPalabras);
    }
    public void comprobarJuego(){
        boolean palabraCompleta = true;
        if (objAhorcado.getNumIntentos()==6) {
            JOptionPane.showMessageDialog(null, "¡Lo siento te has ahorcado, sigue intentandolo!");
            jbtnIngresarLetra.setEnabled(false);
        }else{
            for (int i = 0; i < objAhorcado.getLetrasPlabra()[0].length; i++) {
                if (objAhorcado.getLetrasPlabra()[1][i] == '1') {
                    palabraCompleta = false;
                }
            }
            if (palabraCompleta) {
                JOptionPane.showMessageDialog(null, "¡Felicidades adivinaste la palabra!");
                jbtnIngresarLetra.setEnabled(false);
            }
        }
    }
    public void actualizarImagen(){
        mostrarImagen(jlblAhorcado, imagenesAhorcado[objAhorcado.getNumIntentos()]);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblLogo = new javax.swing.JLabel();
        jlblPractica = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jlblNumPalabras = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstPalabras = new javax.swing.JList<>();
        jtxtNumPalabras = new javax.swing.JTextField();
        jbtnGenerarP = new javax.swing.JButton();
        jbtnJugar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnIngresarLetra = new javax.swing.JButton();
        jlblLetPalabra = new javax.swing.JLabel();
        jlblPalabraSelec = new javax.swing.JLabel();
        jlblAhorcado = new javax.swing.JLabel();
        jbtnLimpiar = new javax.swing.JButton();
        jlblLetIntentos = new javax.swing.JLabel();
        jlblIntentosFallos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlblPractica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblPractica.setForeground(new java.awt.Color(255, 255, 255));
        jlblPractica.setText("Práctica No. 4. Arreglos String - Char");

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlblTitulo.setText("Juego del Ahorcado");

        jlblNumPalabras.setBackground(new java.awt.Color(0, 0, 0));
        jlblNumPalabras.setForeground(new java.awt.Color(255, 255, 255));
        jlblNumPalabras.setText("Número de palabras a generar:");

        jlstPalabras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlstPalabras);

        jbtnGenerarP.setBackground(new java.awt.Color(0, 0, 0));
        jbtnGenerarP.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGenerarP.setText("Generar palabras");
        jbtnGenerarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerarPActionPerformed(evt);
            }
        });

        jbtnJugar.setBackground(new java.awt.Color(0, 0, 0));
        jbtnJugar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnJugar.setText("Jugar ahora");
        jbtnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJugarActionPerformed(evt);
            }
        });

        jbtnSalir.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnIngresarLetra.setBackground(new java.awt.Color(0, 0, 0));
        jbtnIngresarLetra.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIngresarLetra.setText("Ingresa una letra");
        jbtnIngresarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarLetraActionPerformed(evt);
            }
        });

        jlblLetPalabra.setForeground(new java.awt.Color(255, 255, 255));
        jlblLetPalabra.setText("Palabra seleccionada:");

        jlblPalabraSelec.setForeground(java.awt.Color.red);
        jlblPalabraSelec.setText("[...]");

        jlblAhorcado.setBackground(new java.awt.Color(255, 255, 255));
        jlblAhorcado.setOpaque(true);

        jbtnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        jbtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLimpiar.setText("Limpiar juego");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jlblLetIntentos.setForeground(new java.awt.Color(255, 255, 255));
        jlblLetIntentos.setText("Intentos fallidos:");

        jlblIntentosFallos.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jbtnIngresarLetra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(jbtnSalir)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblLetIntentos)
                            .addComponent(jlblLetPalabra))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPractica, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNumPalabras)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtNumPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlblIntentosFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLimpiar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnGenerarP)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnJugar))
                            .addComponent(jlblAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPalabraSelec)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblNumPalabras)
                            .addComponent(jtxtNumPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnGenerarP)
                            .addComponent(jbtnJugar))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlblPractica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblTitulo)
                        .addGap(80, 80, 80)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnIngresarLetra)
                            .addComponent(jbtnSalir)
                            .addComponent(jbtnLimpiar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblLetPalabra)
                            .addComponent(jlblPalabraSelec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblLetIntentos)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblAhorcado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblIntentosFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(102, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        objAhorcado.limpiarObjetos();
        limpiarControles();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnGenerarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerarPActionPerformed
        // TODO add your handling code here
        //objAhorcado.setNumIntentos(0);
        limpiarControles();
        jbtnIngresarLetra.setEnabled(true);
        jbtnJugar.setEnabled(true);
        jbtnLimpiar.setEnabled(true);
        objAhorcado.generarNumPalabras();
        //jlblIntentosFallos.setText(String.valueOf(objAhorcado.getNumIntentos()));
        jtxtNumPalabras.setText(String.valueOf(objAhorcado.getNumPalabras()));
        arrPalabras = new String[2][objAhorcado.getNumPalabras()];
        // Preparar arreglo
        for (int i = 0; i < objAhorcado.getNumPalabras(); i++) {
            arrPalabras[0][i] = "";
            arrPalabras[1][i] = "0";
        }
        JOptionPane.showMessageDialog(null, "Ingresa " + objAhorcado.getNumPalabras() + " palabras:");
        for (int i = 0; i < objAhorcado.getNumPalabras(); i++) {
            while (repetirPalabra) {                
                valorLstP = JOptionPane.showInputDialog(null, "Ingresa la palabra " + (i+1) + ":");
                if (objAhorcado.validadPalabra(valorLstP, arrPalabras) == 0) {
                    arrPalabras[0][i] = objAhorcado.normalizarPalabra(valorLstP);
                    repetirPalabra = false;
                } else if (objAhorcado.validadPalabra(valorLstP, arrPalabras) == 1){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra de mímino 2 letras");
                } else if (objAhorcado.validadPalabra(valorLstP, arrPalabras) == 2){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra sin espacios");
                } else if (objAhorcado.validadPalabra(valorLstP, arrPalabras) == 3){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra que no hayas ingresado antes");
                } else if (objAhorcado.validadPalabra(valorLstP, arrPalabras) == 4){
                    JOptionPane.showMessageDialog(null, "Ingresa solo letras, no números o símbolos");
                } else if (objAhorcado.validadPalabra(valorLstP, arrPalabras) == 5){
                    JOptionPane.showMessageDialog(null, "Ingresa una palabra que no incluya la letra ñ");
                }
            }
            repetirPalabra = true;
        }
        lstPalabras.clear();
        for (int i = 0; i < arrPalabras[0].length; i++) {
            lstPalabras.addElement(arrPalabras[0][i]);
        }
        objAhorcado.setPalabras(arrPalabras);
        // Solo si se quiere jugar inmediatamente:
        // objAhorcado.seleccionarPalabra();
        // jlblIntentosFallos.setText(String.valueOf(objAhorcado.getNumIntentos()));
        // actualizarGuiones();
    }//GEN-LAST:event_jbtnGenerarPActionPerformed

    private void jbtnIngresarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarLetraActionPerformed
        // TODO add your handling code here:
        String letraIngresada = "";
        int rValidar;
        repetirPalabra = true; // Será repetir letra
        while (repetirPalabra) {
            letraIngresada = JOptionPane.showInputDialog(null, "Ingresa una letra:");
            rValidar = objAhorcado.validarLetra(letraIngresada);
            if (rValidar == 0) {
                letraIngresada = objAhorcado.normalizarPalabra(letraIngresada);
                repetirPalabra = false;
                 if(!objAhorcado.compararLetra(letraIngresada)){
                JOptionPane.showMessageDialog(null, "Intento fallido, prueba con otra letra");
            }
            } else if (rValidar == 1) {
                JOptionPane.showMessageDialog(null, "No ingreses más de una letra o espacios vacios");
            } else if (rValidar == 2) {
                JOptionPane.showMessageDialog(null, "Ingresa una letra sin espacios");
            } else if (rValidar == 3) {
                JOptionPane.showMessageDialog(null, "Ingresa una letra que no hayas ingresado antes, esto se cuenta como 1 error");
            } else if (rValidar == 4) {
                JOptionPane.showMessageDialog(null, "Ingresa solo letras, no números o símbolos");
            } else if (rValidar == 5) {
                JOptionPane.showMessageDialog(null, "Ingresa una letra diferente a la ñ");
            }
            jlblIntentosFallos.setText(String.valueOf(objAhorcado.getNumIntentos()));
           
            jlblIntentosFallos.setText(String.valueOf(objAhorcado.getNumIntentos()));
            actualizarGuiones();
            comprobarJuego();
            actualizarImagen();
            if(objAhorcado.getNumIntentos() == 6){
                break;
            }
           
        }
        
    }//GEN-LAST:event_jbtnIngresarLetraActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJugarActionPerformed
        // TODO add your handling code here
        if (!objAhorcado.seleccionarPalabra()) {
            jlblPalabraSelec.setText(objAhorcado.getPalabraSeleccionada());
            JOptionPane.showMessageDialog(null, "El juego ha terminado, por favor genere más palabras");
        }else{
            actualizarGuiones();
            jbtnIngresarLetra.setEnabled(true);
        }
        objAhorcado.setNumIntentos(0);
        jlblIntentosFallos.setText(String.valueOf(objAhorcado.getNumIntentos()));
        actualizarImagen();
        
    }//GEN-LAST:event_jbtnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnGenerarP;
    private javax.swing.JButton jbtnIngresarLetra;
    private javax.swing.JButton jbtnJugar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JLabel jlblAhorcado;
    private javax.swing.JLabel jlblIntentosFallos;
    private javax.swing.JLabel jlblLetIntentos;
    private javax.swing.JLabel jlblLetPalabra;
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JLabel jlblNumPalabras;
    private javax.swing.JLabel jlblPalabraSelec;
    private javax.swing.JLabel jlblPractica;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JList<String> jlstPalabras;
    private javax.swing.JTextField jtxtNumPalabras;
    // End of variables declaration//GEN-END:variables
}
